if: branch !~ ^v\d
language: node_js
node_js: node
jobs:
  include:
  - dist: xenial
    after_success: node_modules/.bin/nyc report --reporter=text-lcov | npx coveralls
  - os: windows
    script: node test.js && node test-stdin.js < .gitattributes
